### ISSUE TITLE
JS-T: Get post content and details

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#17]
Get post content and details

**AC**

- [x] `getContent` with author and permlink
- [x] Explain some of the details of returned object
- [x] Display post in meaningful UI

**Comment by feruzm** [comment]
* Predefined set of posts which has simple markdown content (body) to avoid hassle of explaining different content types
* We can create separate tutorial for consensus details (pending payouts, curation rewards, author rewards, etc.)

**Comment by inertia186** [comment]
I see `details` as including things like the peculiarities of individual fields, not just the format of the body, as well as the different behaviors of certain fields depending on the time since the comment was broadcasted, e.g.: "first_payout" vs "archived" and how that also affects details.

Some Gotchas:
* reading the result of `get_content` is the differences between `total_payout_value` `curator_payout_value` `pending_payout_value` and `total_pending_payout_value`
* determine if the result is a `post` or `comment`.  The way `steemd` does it is to look at `parent_author` (empty string is a `post`), but I've noticed a lot of scripts look at `depth` instead.
* `reblogged_by` isn't being set by `steemd` last time I checked so it should be ignored.
* `json_metadata` may not always contain valid `json`.

**Comment by feruzm** [comment]
So shall we use archived posts as an example and have separate tutorial to talk more about consensus details (author reward, curation, payout cycle, pending, total, etc.) Or we do simple tutorial here and on devportal we explain these more in-depth?

**Comment by inertia186** [comment]
2de1f40347bc360fb9235566e73adabdd524abe9
