### ISSUE TITLE
JS-T: Vote on content (upvote, downvote)

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#28]
Vote post/comment (upvote, downvote)

**AC**

- [x] Voting slider to adjust weight
- [x] Vote on content, explain input parameters

**Addtional AC**
- [x] Add test content to testnet to vote on
- [x] Add visual feedback on vote result

**Comment by rudyardcatling** [comment]
i actually wouldnt dare make comments here but since you asked ...

personally i'm just looking for the most basic way to perform votes and sending sbd or steem for distribution by a bot using only linux shell (bash / dash) and if needs be curl. I'm not a veteran coder but i'm not overly bad at figuring out either, though i do feel completely off-topic here atm lol

since you asked .. here i am

i have all the stats  i need from https://github.com/steemit/devportal/blob/master/_data/apidefinitions/condenser_api.yml and the .json extension to posts and accounts but no clue how to vote or send sbd

i hope this doesnt get flagged lol, but thanks anyway

**Comment by relativityboy** [comment]
@roboza - where is the PR?

**Comment by roboza** [comment]
PR #88
