### ISSUE TITLE
JS-T: Witness listing/voting/unvoting

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal-tutorials-js#38]
Witness listing/voting/unvoting

**AC**

- [x] List all witnesses (50-100), short overview of parameters 
- [x] Voting/Approving and Unvoting/Unapprove witnesses
- [x] Explanation and ref links about witnesses, hot signing (steemconnect)

**Comment by inertia186** [comment]
Also might be good to perhaps keep in mind: "switching a witnesses."  This is something I made up: Unvoting for one witness while simultaneously voting for another witness *in the same transaction*.

The thing that makes this a little unintuitive is that notion that the blockchain *allows* this to happen even if you've already voted for 30 witnesses.

Maybe there's nothing to document in our tutorials about this because it works as one would expect.  I just think it's interesting.
